info:
  component: Zuul Server - Load Balancer

server:
  port: 9000

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
zuul:
  sensitive-headers: Cookie,Set-Cookie

#logging:
#  level:
#    org.springframework: DEBUG


